### PR TITLE
Fix linting errors and enable linting when running molecule test

### PR DESCRIPTION
**Pull request by mcflis**
- Fixed errors raised by linters
- linting according to https://molecule.readthedocs.io/en/latest/configuration.html#lint but in separate script file

### CODE REVIEW

**Review by rummsi1337 — APPROVED** [review]
sexy

**Comment by rummsi1337** [comment]
@mcflis should we merge this?

**Comment by mcflis** [comment]
Yes, let's merge it!

**Comment by rummsi1337** [comment]
Geil

**Pull request merged**
